language: objective-c

os: osx
osx_image: xcode7.1
sudo: false

cache:
  directories:
    - j2objcDist

env:
  - LATEST_JAVA=true
  - LATEST_JAVA=false

before_install:
  - chmod +x gradlew
  - chmod +x scripts/setupJ2OBJC.sh
  - chmod +x scripts/installJava.sh
  - ./scripts/setupJ2OBJC.sh true
  - ./scripts/installJava.sh

script:
  - ./gradlew -b build-prod.gradle
  - rm -rf j2objcDist/j2object-1.1