language: objective-c

os: osx
osx_image: xcode7.1
sudo: false

env:
  - LATEST_JAVA=true
  - LATEST_JAVA=false

before_install:
  - chmod +x gradlew
  - chmod +x scripts/setupJ2OBJC.sh
  - chmod +x scripts/installJava.sh
  - ./scripts/setupJ2OBJC.sh
  - ./scripts/installJava.sh

script:
  - ./gradlew cucumber

 after_script:
  - chmod +x scripts/publishJar.sh
  - ./scripts/publishJar.sh $BINTRAY_API_KEY ${TRAVIS_TAG}