language: objective-c

os: osx
osx_image: xcode7.1
sudo: false

env:
  - LATEST_JAVA=true
  - LATEST_JAVA=false


before_install:
  - chmod +x gradlew
  - chmod +x setupJ2OBJC.sh
  - chmod +x installJava.sh
  - ./setupJ2OBJC.sh
  - ./installJava.sh

after_script:
  - curl \
      -T "build/libs/deepstream.io.*.jar" \
      -H "X-Bintray-Publish:1" \
      -u yasserf:$BINTRAY_API_KEY \
      "https://api.bintray.com/content/deepstreamio/maven/deepstream.io-client-java/${TRAVIS_TAG}/deepstream.io-client-java_${TRAVIS_TAG}.jar"

script:
  - ./gradlew cucumber